version: '3.2'

services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "7545:8545"

  truffle:
    build:
      context: .
    stdin_open: true
    tty: true
    depends_on:
      - ganache
    volumes:
      - ./build-results:/app/logs:rw